# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
